### PR TITLE
Make `storage_options` consistent with fsspec to be able to pass local cache directory

### PR DESCRIPTION
**Pull request by sanath-2024**
By default, the `simplecache` protocol in `fsspec` creates a new temporary directory to serve as the local cache for a remote filesystem. However, if we want to use an existing local cache, we need the ability to specify an existing directory as the local cache.

### CODE REVIEW

**Comment by sanath-2024** [comment]
For 1, the `simplecache` test wouldn't run until I installed `lockfile`. However, strangely, when I uninstalled `lockfile` the test still ran fine! I will revert the dependencies. I think Poetry was complaining because I had an outdated installation of `lockfile`, since that's the only relevant code I can find that uses `lockfile`.

For 2, I can see a couple of options to pass the local cache directory within the `storage_options` dict itself:

Existing behavior:

```py
# no disk cache: leave options as is
process_url(url="s3://some/path", storage_options={"some key": "some value"}, disk_cache=False, ...)

storage_options == {"some key": "some value"}
```

```py
# disk cache: modify storage options
process_url(url="s3://some/path", storage_options={"some key": "some value"}, disk_cache=True, ...)

storage_options == {"s3": {"some key": "some value"}}
```

Option 1: never modify the input `storage_options`

```py
# no disk cache: leave options as is
process_url(url="s3://some/path", storage_options={"some key": "some value"}, disk_cache=False, ...)

storage_options == {"some key": "some value"}
```

```py
# disk cache: leave options as is (make the user specify their S3 storage options under the "s3" key)
process_url(url="s3://some/path", storage_options={"s3": {"some key": "some value"}}, disk_cache=True, ...)

storage_options == {"s3": {"some key": "some value"}}
```

```py
# disk cache with custom storage directory: leave options as is (make the user specify which options are going to each FS)
process_url(url="s3://some/path", storage_options={"s3": {"some key": "some value"}, "simplecache": {"cache_storage": "/local/path"}}, disk_cache=True, ...)

storage_options == {"s3": {"some key": "some value"}, "simplecache": {"cache_storage": "/local/path"}}
```

Option 2: move the `cache_storage` option to where it needs to go

```py
# no disk cache: leave options as is
process_url(url="s3://some/path", storage_options={"some key": "some value"}, disk_cache=False, ...)

storage_options == {"some key": "some value"}
```

```py
# disk cache: modify storage options
process_url(url="s3://some/path", storage_options={"some key": "some value"}, disk_cache=True, ...)

storage_options == {"s3": {"some key": "some value"}}
```

```py
# disk cache with custom storage directory: assume that only the `cache_storage` option is going to `simplecache`, put all other options in `s3`, `gcs`, etc.
process_url(url="s3://some/path", storage_options={"some key": "some value", "cache_storage": "/local/path"}, disk_cache=True, ...)

storage_options == {"s3": {"some key": "some value"}, "simplecache": {"cache_storage": "/local/path"}}
```

Option 1 would be more flexible, since users could specify which options go to which FS. However, option 2 would be more compatible with existing solutions and would be easier to use (although its interface would be significantly different from the `fsspec` interface).

Which one would you recommend? Or were you thinking of something else?

**Comment by tasansal** [comment]
I am leaning towards option 1 to be directly compatible with `fsspec`. 

Option 2 is nice too but it is less explicit. 

We need to write docs with examples for either. 

I am voting option 1, let's ask what @srib thinks.

**Comment by srib** [comment]
I think option 1 is easy to understand, explicit and compatible with
`fsspec`. I would prefer that over option 2.

In any case, we need to document the use case well because of too many
key-value pairs in the storage options!

**Comment by tasansal** [comment]
Thanks @sanath-2024! Code changes look good to me. Can we move the comments into the doctoring and add some in the examples section? 

See here for docstring example.

I will merge this after the docstring update but needs to be tested with combining a cloud provider options and simple cache before next release.

**Comment by tasansal** [comment]
@sanath-2024 I suggested adding the doctest style strings, so it gets rendered as code in the documentation. Also, added slightly more detail to the docstring you wrote. LGTM besides that!

**Review by tasansal — CHANGES_REQUESTED** [review]

**Comment by tasansal** [comment]
Oops broke the linter, I'll fix it and merge.

**Review by tasansal — APPROVED** [review]

**Pull request merged**
